// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: streamexa/plugin/v1/plugin.proto

// Package streamexa.plugin.v1 is the go-plugin gRPC contract between the Go
// analyzer host and a Go plugin. PluginService is implemented by the plugin and
// called by the host (Run). HostService is implemented by the host and called
// back by the plugin over the go-plugin broker reverse channel for the
// whitelisted actions. Plugins never receive raw CDP/Playwright objects.

package pluginpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RunRequest carries the initial read-only snapshot plus the go-plugin broker id
// the plugin dials to reach the host's reverse HostService.
type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *PageSnapshot          `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	HostBrokerId  uint32                 `protobuf:"varint,2,opt,name=host_broker_id,json=hostBrokerId,proto3" json:"host_broker_id,omitempty"`
	TargetUrl     string                 `protobuf:"bytes,3,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_streamexa_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetSnapshot() *PageSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *RunRequest) GetHostBrokerId() uint32 {
	if x != nil {
		return x.HostBrokerId
	}
	return 0
}

func (x *RunRequest) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *PluginResult          `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_streamexa_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *RunResponse) GetResult() *PluginResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// PageSnapshot is the read-only view of the current CDP context: DOM, iframes,
// completed requests (headers redacted), and native stream analysis results. It
// carries no response bodies.
type PageSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageDom       string                 `protobuf:"bytes,1,opt,name=page_dom,json=pageDom,proto3" json:"page_dom,omitempty"`
	Iframes       []*IFrameDom           `protobuf:"bytes,2,rep,name=iframes,proto3" json:"iframes,omitempty"`
	Requests      []*CapturedRequest     `protobuf:"bytes,3,rep,name=requests,proto3" json:"requests,omitempty"`
	StreamResults []*AnalyzedSource      `protobuf:"bytes,4,rep,name=stream_results,json=streamResults,proto3" json:"stream_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageSnapshot) Reset() {
	*x = PageSnapshot{}
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageSnapshot) ProtoMessage() {}

func (x *PageSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageSnapshot.ProtoReflect.Descriptor instead.
func (*PageSnapshot) Descriptor() ([]byte, []int) {
	return file_streamexa_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PageSnapshot) GetPageDom() string {
	if x != nil {
		return x.PageDom
	}
	return ""
}

func (x *PageSnapshot) GetIframes() []*IFrameDom {
	if x != nil {
		return x.Iframes
	}
	return nil
}

func (x *PageSnapshot) GetRequests() []*CapturedRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *PageSnapshot) GetStreamResults() []*AnalyzedSource {
	if x != nil {
		return x.StreamResults
	}
	return nil
}

type IFrameDom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameUrl      string                 `protobuf:"bytes,1,opt,name=frame_url,json=frameUrl,proto3" json:"frame_url,omitempty"`
	Dom           string                 `protobuf:"bytes,2,opt,name=dom,proto3" json:"dom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IFrameDom) Reset() {
	*x = IFrameDom{}
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IFrameDom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IFrameDom) ProtoMessage() {}

func (x *IFrameDom) ProtoReflect() protoreflect.Message {
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IFrameDom.ProtoReflect.Descriptor instead.
func (*IFrameDom) Descriptor() ([]byte, []int) {
	return file_streamexa_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *IFrameDom) GetFrameUrl() string {
	if x != nil {
		return x.FrameUrl
	}
	return ""
}

func (x *IFrameDom) GetDom() string {
	if x != nil {
		return x.Dom
	}
	return ""
}

type CapturedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	ResourceType  string                 `protobuf:"bytes,5,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MediaType     string                 `protobuf:"bytes,7,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	VideoDuration float64                `protobuf:"fixed64,8,opt,name=video_duration,json=videoDuration,proto3" json:"video_duration,omitempty"`
	IsAd          bool                   `protobuf:"varint,9,opt,name=is_ad,json=isAd,proto3" json:"is_ad,omitempty"`
	IsLiveStream  bool                   `protobuf:"varint,10,opt,name=is_live_stream,json=isLiveStream,proto3" json:"is_live_stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapturedRequest) Reset() {
	*x = CapturedRequest{}
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapturedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapturedRequest) ProtoMessage() {}

func (x *CapturedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapturedRequest.ProtoReflect.Descriptor instead.
func (*CapturedRequest) Descriptor() ([]byte, []int) {
	return file_streamexa_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *CapturedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CapturedRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CapturedRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CapturedRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CapturedRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *CapturedRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CapturedRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *CapturedRequest) GetVideoDuration() float64 {
	if x != nil {
		return x.VideoDuration
	}
	return 0
}

func (x *CapturedRequest) GetIsAd() bool {
	if x != nil {
		return x.IsAd
	}
	return false
}

func (x *CapturedRequest) GetIsLiveStream() bool {
	if x != nil {
		return x.IsLiveStream
	}
	return false
}

// AnalyzedSource mirrors the host's detection.AnalyzedSource shape.
type AnalyzedSource struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Url            string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	RequestHeaders map[string]string      `protobuf:"bytes,2,rep,name=request_headers,json=requestHeaders,proto3" json:"request_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MimeType       string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	VideoDuration  float64                `protobuf:"fixed64,4,opt,name=video_duration,json=videoDuration,proto3" json:"video_duration,omitempty"`
	EstimatedBytes int64                  `protobuf:"varint,5,opt,name=estimated_bytes,json=estimatedBytes,proto3" json:"estimated_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzedSource) Reset() {
	*x = AnalyzedSource{}
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzedSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzedSource) ProtoMessage() {}

func (x *AnalyzedSource) ProtoReflect() protoreflect.Message {
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzedSource.ProtoReflect.Descriptor instead.
func (*AnalyzedSource) Descriptor() ([]byte, []int) {
	return file_streamexa_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *AnalyzedSource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AnalyzedSource) GetRequestHeaders() map[string]string {
	if x != nil {
		return x.RequestHeaders
	}
	return nil
}

func (x *AnalyzedSource) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *AnalyzedSource) GetVideoDuration() float64 {
	if x != nil {
		return x.VideoDuration
	}
	return 0
}

func (x *AnalyzedSource) GetEstimatedBytes() int64 {
	if x != nil {
		return x.EstimatedBytes
	}
	return 0
}

// PluginResult is exactly {sources, task?, metadata?}.
type PluginResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*AnalyzedSource      `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	Task          *PluginTask            `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginResult) Reset() {
	*x = PluginResult{}
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginResult) ProtoMessage() {}

func (x *PluginResult) ProtoReflect() protoreflect.Message {
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginResult.ProtoReflect.Descriptor instead.
func (*PluginResult) Descriptor() ([]byte, []int) {
	return file_streamexa_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *PluginResult) GetSources() []*AnalyzedSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *PluginResult) GetTask() *PluginTask {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *PluginResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PluginTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*AnalyzedSource      `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginTask) Reset() {
	*x = PluginTask{}
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginTask) ProtoMessage() {}

func (x *PluginTask) ProtoReflect() protoreflect.Message {
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginTask.ProtoReflect.Descriptor instead.
func (*PluginTask) Descriptor() ([]byte, []int) {
	return file_streamexa_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *PluginTask) GetSources() []*AnalyzedSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *PluginTask) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type GetResponseBodyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponseBodyRequest) Reset() {
	*x = GetResponseBodyRequest{}
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponseBodyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponseBodyRequest) ProtoMessage() {}

func (x *GetResponseBodyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponseBodyRequest.ProtoReflect.Descriptor instead.
func (*GetResponseBodyRequest) Descriptor() ([]byte, []int) {
	return file_streamexa_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *GetResponseBodyRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetResponseBodyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponseBodyResponse) Reset() {
	*x = GetResponseBodyResponse{}
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponseBodyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponseBodyResponse) ProtoMessage() {}

func (x *GetResponseBodyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponseBodyResponse.ProtoReflect.Descriptor instead.
func (*GetResponseBodyResponse) Descriptor() ([]byte, []int) {
	return file_streamexa_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *GetResponseBodyResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponseBodyResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ClickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      string                 `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickRequest) Reset() {
	*x = ClickRequest{}
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickRequest) ProtoMessage() {}

func (x *ClickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickRequest.ProtoReflect.Descriptor instead.
func (*ClickRequest) Descriptor() ([]byte, []int) {
	return file_streamexa_plugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ClickRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

type WaitForRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one of selector or timeout_ms is used: a non-empty selector waits
	// for that element; otherwise timeout_ms waits a fixed duration.
	Selector      string `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	TimeoutMs     int64  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForRequest) Reset() {
	*x = WaitForRequest{}
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForRequest) ProtoMessage() {}

func (x *WaitForRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForRequest.ProtoReflect.Descriptor instead.
func (*WaitForRequest) Descriptor() ([]byte, []int) {
	return file_streamexa_plugin_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *WaitForRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *WaitForRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ClickResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickResponse) Reset() {
	*x = ClickResponse{}
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickResponse) ProtoMessage() {}

func (x *ClickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickResponse.ProtoReflect.Descriptor instead.
func (*ClickResponse) Descriptor() ([]byte, []int) {
	return file_streamexa_plugin_v1_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *ClickResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ClickResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WaitForResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForResponse) Reset() {
	*x = WaitForResponse{}
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForResponse) ProtoMessage() {}

func (x *WaitForResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForResponse.ProtoReflect.Descriptor instead.
func (*WaitForResponse) Descriptor() ([]byte, []int) {
	return file_streamexa_plugin_v1_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *WaitForResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *WaitForResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_streamexa_plugin_v1_plugin_proto_rawDescGZIP(), []int{14}
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *PageSnapshot          `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_streamexa_plugin_v1_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *SnapshotResponse) GetSnapshot() *PageSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_streamexa_plugin_v1_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *FetchRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FetchRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *FetchRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *FetchRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_streamexa_plugin_v1_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *FetchResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FetchResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *FetchResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_streamexa_plugin_v1_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *LogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_streamexa_plugin_v1_plugin_proto_rawDescGZIP(), []int{19}
}

type PlayVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayVideosRequest) Reset() {
	*x = PlayVideosRequest{}
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayVideosRequest) ProtoMessage() {}

func (x *PlayVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayVideosRequest.ProtoReflect.Descriptor instead.
func (*PlayVideosRequest) Descriptor() ([]byte, []int) {
	return file_streamexa_plugin_v1_plugin_proto_rawDescGZIP(), []int{20}
}

type PlayVideosResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// clicked is the number of <video> elements successfully clicked across all
	// frames. Zero clicks (no video / all clicks failed) is ok=true, not an error.
	Clicked       int32  `protobuf:"varint,1,opt,name=clicked,proto3" json:"clicked,omitempty"`
	Ok            bool   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayVideosResponse) Reset() {
	*x = PlayVideosResponse{}
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayVideosResponse) ProtoMessage() {}

func (x *PlayVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamexa_plugin_v1_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayVideosResponse.ProtoReflect.Descriptor instead.
func (*PlayVideosResponse) Descriptor() ([]byte, []int) {
	return file_streamexa_plugin_v1_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *PlayVideosResponse) GetClicked() int32 {
	if x != nil {
		return x.Clicked
	}
	return 0
}

func (x *PlayVideosResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PlayVideosResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_streamexa_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_streamexa_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	" streamexa/plugin/v1/plugin.proto\x12\x13streamexa.plugin.v1\"\x90\x01\n" +
	"\n" +
	"RunRequest\x12=\n" +
	"\bsnapshot\x18\x01 \x01(\v2!.streamexa.plugin.v1.PageSnapshotR\bsnapshot\x12$\n" +
	"\x0ehost_broker_id\x18\x02 \x01(\rR\fhostBrokerId\x12\x1d\n" +
	"\n" +
	"target_url\x18\x03 \x01(\tR\ttargetUrl\"H\n" +
	"\vRunResponse\x129\n" +
	"\x06result\x18\x01 \x01(\v2!.streamexa.plugin.v1.PluginResultR\x06result\"\xf1\x01\n" +
	"\fPageSnapshot\x12\x19\n" +
	"\bpage_dom\x18\x01 \x01(\tR\apageDom\x128\n" +
	"\aiframes\x18\x02 \x03(\v2\x1e.streamexa.plugin.v1.IFrameDomR\aiframes\x12@\n" +
	"\brequests\x18\x03 \x03(\v2$.streamexa.plugin.v1.CapturedRequestR\brequests\x12J\n" +
	"\x0estream_results\x18\x04 \x03(\v2#.streamexa.plugin.v1.AnalyzedSourceR\rstreamResults\":\n" +
	"\tIFrameDom\x12\x1b\n" +
	"\tframe_url\x18\x01 \x01(\tR\bframeUrl\x12\x10\n" +
	"\x03dom\x18\x02 \x01(\tR\x03dom\"\x92\x03\n" +
	"\x0fCapturedRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12#\n" +
	"\rresource_type\x18\x05 \x01(\tR\fresourceType\x12K\n" +
	"\aheaders\x18\x06 \x03(\v21.streamexa.plugin.v1.CapturedRequest.HeadersEntryR\aheaders\x12\x1d\n" +
	"\n" +
	"media_type\x18\a \x01(\tR\tmediaType\x12%\n" +
	"\x0evideo_duration\x18\b \x01(\x01R\rvideoDuration\x12\x13\n" +
	"\x05is_ad\x18\t \x01(\bR\x04isAd\x12$\n" +
	"\x0eis_live_stream\x18\n" +
	" \x01(\bR\fisLiveStream\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x02\n" +
	"\x0eAnalyzedSource\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12`\n" +
	"\x0frequest_headers\x18\x02 \x03(\v27.streamexa.plugin.v1.AnalyzedSource.RequestHeadersEntryR\x0erequestHeaders\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12%\n" +
	"\x0evideo_duration\x18\x04 \x01(\x01R\rvideoDuration\x12'\n" +
	"\x0festimated_bytes\x18\x05 \x01(\x03R\x0eestimatedBytes\x1aA\n" +
	"\x13RequestHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x02\n" +
	"\fPluginResult\x12=\n" +
	"\asources\x18\x01 \x03(\v2#.streamexa.plugin.v1.AnalyzedSourceR\asources\x123\n" +
	"\x04task\x18\x02 \x01(\v2\x1f.streamexa.plugin.v1.PluginTaskR\x04task\x12K\n" +
	"\bmetadata\x18\x03 \x03(\v2/.streamexa.plugin.v1.PluginResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x01\n" +
	"\n" +
	"PluginTask\x12=\n" +
	"\asources\x18\x01 \x03(\v2#.streamexa.plugin.v1.AnalyzedSourceR\asources\x12C\n" +
	"\x06labels\x18\x02 \x03(\v2+.streamexa.plugin.v1.PluginTask.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\x16GetResponseBodyRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"C\n" +
	"\x17GetResponseBodyResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\"*\n" +
	"\fClickRequest\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\"K\n" +
	"\x0eWaitForRequest\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x03R\ttimeoutMs\"5\n" +
	"\rClickResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"7\n" +
	"\x0fWaitForResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x11\n" +
	"\x0fSnapshotRequest\"Q\n" +
	"\x10SnapshotResponse\x12=\n" +
	"\bsnapshot\x18\x01 \x01(\v2!.streamexa.plugin.v1.PageSnapshotR\bsnapshot\"\xd2\x01\n" +
	"\fFetchRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12H\n" +
	"\aheaders\x18\x03 \x03(\v2..streamexa.plugin.v1.FetchRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc2\x01\n" +
	"\rFetchResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12I\n" +
	"\aheaders\x18\x02 \x03(\v2/.streamexa.plugin.v1.FetchResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\n" +
	"LogRequest\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\r\n" +
	"\vLogResponse\"\x13\n" +
	"\x11PlayVideosRequest\"T\n" +
	"\x12PlayVideosResponse\x12\x18\n" +
	"\aclicked\x18\x01 \x01(\x05R\aclicked\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2Y\n" +
	"\rPluginService\x12H\n" +
	"\x03Run\x12\x1f.streamexa.plugin.v1.RunRequest\x1a .streamexa.plugin.v1.RunResponse2\xf3\x04\n" +
	"\vHostService\x12l\n" +
	"\x0fGetResponseBody\x12+.streamexa.plugin.v1.GetResponseBodyRequest\x1a,.streamexa.plugin.v1.GetResponseBodyResponse\x12N\n" +
	"\x05Click\x12!.streamexa.plugin.v1.ClickRequest\x1a\".streamexa.plugin.v1.ClickResponse\x12T\n" +
	"\aWaitFor\x12#.streamexa.plugin.v1.WaitForRequest\x1a$.streamexa.plugin.v1.WaitForResponse\x12W\n" +
	"\bSnapshot\x12$.streamexa.plugin.v1.SnapshotRequest\x1a%.streamexa.plugin.v1.SnapshotResponse\x12N\n" +
	"\x05Fetch\x12!.streamexa.plugin.v1.FetchRequest\x1a\".streamexa.plugin.v1.FetchResponse\x12H\n" +
	"\x03Log\x12\x1f.streamexa.plugin.v1.LogRequest\x1a .streamexa.plugin.v1.LogResponse\x12]\n" +
	"\n" +
	"PlayVideos\x12&.streamexa.plugin.v1.PlayVideosRequest\x1a'.streamexa.plugin.v1.PlayVideosResponseB<Z:github.com/lanyitin/streamexa-plugin-sdk/pluginpb;pluginpbb\x06proto3"

var (
	file_streamexa_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_streamexa_plugin_v1_plugin_proto_rawDescData []byte
)

func file_streamexa_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_streamexa_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_streamexa_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamexa_plugin_v1_plugin_proto_rawDesc), len(file_streamexa_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_streamexa_plugin_v1_plugin_proto_rawDescData
}

var file_streamexa_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_streamexa_plugin_v1_plugin_proto_goTypes = []any{
	(*RunRequest)(nil),              // 0: streamexa.plugin.v1.RunRequest
	(*RunResponse)(nil),             // 1: streamexa.plugin.v1.RunResponse
	(*PageSnapshot)(nil),            // 2: streamexa.plugin.v1.PageSnapshot
	(*IFrameDom)(nil),               // 3: streamexa.plugin.v1.IFrameDom
	(*CapturedRequest)(nil),         // 4: streamexa.plugin.v1.CapturedRequest
	(*AnalyzedSource)(nil),          // 5: streamexa.plugin.v1.AnalyzedSource
	(*PluginResult)(nil),            // 6: streamexa.plugin.v1.PluginResult
	(*PluginTask)(nil),              // 7: streamexa.plugin.v1.PluginTask
	(*GetResponseBodyRequest)(nil),  // 8: streamexa.plugin.v1.GetResponseBodyRequest
	(*GetResponseBodyResponse)(nil), // 9: streamexa.plugin.v1.GetResponseBodyResponse
	(*ClickRequest)(nil),            // 10: streamexa.plugin.v1.ClickRequest
	(*WaitForRequest)(nil),          // 11: streamexa.plugin.v1.WaitForRequest
	(*ClickResponse)(nil),           // 12: streamexa.plugin.v1.ClickResponse
	(*WaitForResponse)(nil),         // 13: streamexa.plugin.v1.WaitForResponse
	(*SnapshotRequest)(nil),         // 14: streamexa.plugin.v1.SnapshotRequest
	(*SnapshotResponse)(nil),        // 15: streamexa.plugin.v1.SnapshotResponse
	(*FetchRequest)(nil),            // 16: streamexa.plugin.v1.FetchRequest
	(*FetchResponse)(nil),           // 17: streamexa.plugin.v1.FetchResponse
	(*LogRequest)(nil),              // 18: streamexa.plugin.v1.LogRequest
	(*LogResponse)(nil),             // 19: streamexa.plugin.v1.LogResponse
	(*PlayVideosRequest)(nil),       // 20: streamexa.plugin.v1.PlayVideosRequest
	(*PlayVideosResponse)(nil),      // 21: streamexa.plugin.v1.PlayVideosResponse
	nil,                             // 22: streamexa.plugin.v1.CapturedRequest.HeadersEntry
	nil,                             // 23: streamexa.plugin.v1.AnalyzedSource.RequestHeadersEntry
	nil,                             // 24: streamexa.plugin.v1.PluginResult.MetadataEntry
	nil,                             // 25: streamexa.plugin.v1.PluginTask.LabelsEntry
	nil,                             // 26: streamexa.plugin.v1.FetchRequest.HeadersEntry
	nil,                             // 27: streamexa.plugin.v1.FetchResponse.HeadersEntry
}
var file_streamexa_plugin_v1_plugin_proto_depIdxs = []int32{
	2,  // 0: streamexa.plugin.v1.RunRequest.snapshot:type_name -> streamexa.plugin.v1.PageSnapshot
	6,  // 1: streamexa.plugin.v1.RunResponse.result:type_name -> streamexa.plugin.v1.PluginResult
	3,  // 2: streamexa.plugin.v1.PageSnapshot.iframes:type_name -> streamexa.plugin.v1.IFrameDom
	4,  // 3: streamexa.plugin.v1.PageSnapshot.requests:type_name -> streamexa.plugin.v1.CapturedRequest
	5,  // 4: streamexa.plugin.v1.PageSnapshot.stream_results:type_name -> streamexa.plugin.v1.AnalyzedSource
	22, // 5: streamexa.plugin.v1.CapturedRequest.headers:type_name -> streamexa.plugin.v1.CapturedRequest.HeadersEntry
	23, // 6: streamexa.plugin.v1.AnalyzedSource.request_headers:type_name -> streamexa.plugin.v1.AnalyzedSource.RequestHeadersEntry
	5,  // 7: streamexa.plugin.v1.PluginResult.sources:type_name -> streamexa.plugin.v1.AnalyzedSource
	7,  // 8: streamexa.plugin.v1.PluginResult.task:type_name -> streamexa.plugin.v1.PluginTask
	24, // 9: streamexa.plugin.v1.PluginResult.metadata:type_name -> streamexa.plugin.v1.PluginResult.MetadataEntry
	5,  // 10: streamexa.plugin.v1.PluginTask.sources:type_name -> streamexa.plugin.v1.AnalyzedSource
	25, // 11: streamexa.plugin.v1.PluginTask.labels:type_name -> streamexa.plugin.v1.PluginTask.LabelsEntry
	2,  // 12: streamexa.plugin.v1.SnapshotResponse.snapshot:type_name -> streamexa.plugin.v1.PageSnapshot
	26, // 13: streamexa.plugin.v1.FetchRequest.headers:type_name -> streamexa.plugin.v1.FetchRequest.HeadersEntry
	27, // 14: streamexa.plugin.v1.FetchResponse.headers:type_name -> streamexa.plugin.v1.FetchResponse.HeadersEntry
	0,  // 15: streamexa.plugin.v1.PluginService.Run:input_type -> streamexa.plugin.v1.RunRequest
	8,  // 16: streamexa.plugin.v1.HostService.GetResponseBody:input_type -> streamexa.plugin.v1.GetResponseBodyRequest
	10, // 17: streamexa.plugin.v1.HostService.Click:input_type -> streamexa.plugin.v1.ClickRequest
	11, // 18: streamexa.plugin.v1.HostService.WaitFor:input_type -> streamexa.plugin.v1.WaitForRequest
	14, // 19: streamexa.plugin.v1.HostService.Snapshot:input_type -> streamexa.plugin.v1.SnapshotRequest
	16, // 20: streamexa.plugin.v1.HostService.Fetch:input_type -> streamexa.plugin.v1.FetchRequest
	18, // 21: streamexa.plugin.v1.HostService.Log:input_type -> streamexa.plugin.v1.LogRequest
	20, // 22: streamexa.plugin.v1.HostService.PlayVideos:input_type -> streamexa.plugin.v1.PlayVideosRequest
	1,  // 23: streamexa.plugin.v1.PluginService.Run:output_type -> streamexa.plugin.v1.RunResponse
	9,  // 24: streamexa.plugin.v1.HostService.GetResponseBody:output_type -> streamexa.plugin.v1.GetResponseBodyResponse
	12, // 25: streamexa.plugin.v1.HostService.Click:output_type -> streamexa.plugin.v1.ClickResponse
	13, // 26: streamexa.plugin.v1.HostService.WaitFor:output_type -> streamexa.plugin.v1.WaitForResponse
	15, // 27: streamexa.plugin.v1.HostService.Snapshot:output_type -> streamexa.plugin.v1.SnapshotResponse
	17, // 28: streamexa.plugin.v1.HostService.Fetch:output_type -> streamexa.plugin.v1.FetchResponse
	19, // 29: streamexa.plugin.v1.HostService.Log:output_type -> streamexa.plugin.v1.LogResponse
	21, // 30: streamexa.plugin.v1.HostService.PlayVideos:output_type -> streamexa.plugin.v1.PlayVideosResponse
	23, // [23:31] is the sub-list for method output_type
	15, // [15:23] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_streamexa_plugin_v1_plugin_proto_init() }
func file_streamexa_plugin_v1_plugin_proto_init() {
	if File_streamexa_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamexa_plugin_v1_plugin_proto_rawDesc), len(file_streamexa_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_streamexa_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_streamexa_plugin_v1_plugin_proto_depIdxs,
		MessageInfos:      file_streamexa_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_streamexa_plugin_v1_plugin_proto = out.File
	file_streamexa_plugin_v1_plugin_proto_goTypes = nil
	file_streamexa_plugin_v1_plugin_proto_depIdxs = nil
}
